# Práctica 2

In [1]:
import numpy as np

## Solución al primer ejercicio

In [2]:
arr = np.random.randint(0, 101, size=(5, 4, 3))
arr

array([[[10, 57, 60],
        [45, 39, 93],
        [16, 12, 44],
        [80, 85, 64]],

       [[66, 96, 47],
        [56, 54, 76],
        [79, 50,  5],
        [49, 16, 26]],

       [[59, 64, 19],
        [58, 90, 33],
        [25, 70, 34],
        [46,  5,  9]],

       [[34, 42, 66],
        [36, 86, 27],
        [23, 15, 38],
        [ 1, 92, 34]],

       [[76, 80, 73],
        [47, 11, 26],
        [72, 34, 67],
        [90, 65, 74]]])

In [3]:
min_val = np.min(arr)
max_val = np.max(arr)

min_val, max_val

(np.int64(1), np.int64(96))

In [9]:
pos_min = np.argwhere(arr == min_val)[0]
pos_max = np.argwhere(arr == max_val)[0]

pos_min, pos_max

(array([3, 3, 0]), array([1, 0, 1]))

In [11]:
# print("Arreglo generado:\n", arr)
print(f"\nValor mínimo: {min_val} en la posición: {tuple(pos_min)}")
print(f"\nValor máximo: {max_val} en la posición: {tuple(pos_max)}")


Valor mínimo: 1 en la posición: (np.int64(3), np.int64(3), np.int64(0))

Valor máximo: 96 en la posición: (np.int64(1), np.int64(0), np.int64(1))


## Solución al segundo ejercicio

In [17]:
H = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
H

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
H_transposed = np.transpose(H, axes=(0, 2, 1))
H_transposed

array([[[ 1,  4],
        [ 2,  5],
        [ 3,  6]],

       [[ 7, 10],
        [ 8, 11],
        [ 9, 12]]])

In [19]:
print(f"Matriz original:\n{H}")
print(f"\nMatriz transpuesta:\n{H_transposed}")

Matriz original:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Matriz transpuesta:
[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]
